Repository magento/security-package, pull requests merged in 2020-06, with the labels that each got.

#246 [MFTF] [1.0-develop] MQE-2194: fix mftf tests static check failures
  Securitytxt/Test/Mftf/ActionGroup/FillSecurityTxtConfigurationActionGroup.xml
Labels: Progress: approved

#245 [MFTF] [1.0.0-develop] MQE-2194: fix mftf tests static check failures
  Securitytxt/Test/Mftf/ActionGroup/FillSecurityTxtConfigurationActionGroup.xml
Labels: Progress: approved

#250 MC-35119: U2F Key registration error in Chrome on Ubuntu
  TwoFactorAuth/Model/Provider/Engine/U2fKey/WebAuthn.php
Labels: Component: 2FA, Progress: review, bug

#248 Merge 1.0.0-develop into 1.0.0-master
  ReCaptchaFrontendUi/view/frontend/web/js/nonInlineReCaptchaRenderer.js
  ReCaptchaFrontendUi/view/frontend/web/js/reCaptcha.js
  ReCaptchaNewsletter/etc/adminhtml/system.xml
  ReCaptchaNewsletter/view/frontend/layout/default.xml
  ReCaptchaNewsletter/view/frontend/web/css/source/_module.less
  Securitytxt/Test/Mftf/ActionGroup/FillSecurityTxtConfigurationActionGroup.xml
  TwoFactorAuth/Model/Provider/Engine/U2fKey/WebAuthn.php
Labels: 2.4.0-develop: :one:
