Repository magento/security-package, pull requests merged in 2020-09, with the labels that each got.

#272 [Arrows] MC-34344: AdminLoginAfterJSMinificationTest does not properly enable minification
  TwoFactorAuth/Test/Mftf/Test/AdminLoginAfterJSMinificationTest.xml
Labels: Progress: approved

#270 magento/security-package#269: Browser Shouldn't Suggest Historic 2FA Codes
  TwoFactorAuth/view/adminhtml/web/template/authy/auth.html
  TwoFactorAuth/view/adminhtml/web/template/authy/configure/verify.html
  TwoFactorAuth/view/adminhtml/web/template/google/auth.html
  TwoFactorAuth/view/adminhtml/web/template/google/configure.html
Labels: Component: 2FA, Partner: Vaimo, Progress: approved, bug

#263 Update tfa_tfa_requestconfig.xml
  TwoFactorAuth/view/adminhtml/layout/tfa_tfa_requestconfig.xml
Labels: Component: 2FA, Progress: approved, enhancement
